### ISSUE TITLE
Trouble with redis connection.

### ISSUE THREAD

**Issue by horseyhorsey** [freezy/node-vpdb#35]
Is the Redis server started, anyway to test? I have no idea...

'<2015-11-03T01:50:30.846Z - info: [model] Schema "Build" registered.
2015-11-03T01:50:30.860Z - info: [model] Schema "Comment" registered.
2015-11-03T01:50:31.282Z - info: [quota] Initializing quotas...
2015-11-03T01:50:31.283Z - info: [quota] Creating quota for credits per day...
2015-11-03T01:50:31.333Z - info: [model] Schema "File" registered.
2015-11-03T01:50:31.343Z - info: [model] Schema "Game" registered.
2015-11-03T01:50:31.347Z - info: [model] Schema "LogEvent" registered.
2015-11-03T01:50:31.349Z - info: [model] Schema "LogUser" registered.
2015-11-03T01:50:31.350Z - info: [model] Schema "Rating" registered.
2015-11-03T01:50:31.368Z - info: [model] Schema "Release" registered.
2015-11-03T01:50:31.371Z - info: [model] Schema "Rom" registered.
2015-11-03T01:50:31.373Z - info: [model] Schema "Star" registered.
2015-11-03T01:50:31.374Z - info: [model] Schema "Tag" registered.
2015-11-03T01:50:31.377Z - info: [model] Schema "Token" registered.
2015-11-03T01:50:31.384Z - info: [model] Schema "User" registered.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at RedisClient.on_error (I:\PinballX\node-vpdb\node_modules\redis\index.js:196:24)
    at Socket.<anonymous> (I:\PinballX\node-vpdb\node_modules\redis\index.js:106:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at doNTCallback2 (node.js:450:9)
    at process._tickDomainCallback (node.js:405:17)

I:\PinballX\node-vpdb>>'

**Comment by horseyhorsey** [comment]
Starting the server there was a problem with the memory size but run into this database server error.

Is that something to do with mongoDB?

![dbsrror](https://cloud.githubusercontent.com/assets/5377332/10900125/d8946366-81d3-11e5-813c-f02a22df339b.png)

**Comment by freezy** [comment]
Yeah, `27017` is MongoDB. Are you planning to contribute to this? Or just playing around? 

Contrarily to Pind this is not supposed to be "installable by mainstream users" (and even Pind completely missed that goal). You might have a better chance of getting this to run in a Linux VM.
